# Generated by Django 3.2.4 on 2021-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieApp', '0003_rename_name_review_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
