# Generated by Django 3.2.4 on 2021-06-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieApp', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
