from django.urls import path     
from . import views

urlpatterns = [
    path('', views.index),
    path('register_page', views.register_page),
    path('register', views.register),
    path('login_page', views.login_page),
    path('login', views.login),
    path('logout', views.logout),
    path('dashboard', views.dashboard),
    path('explore', views.explore),
    path('collection_page', views.collection_page),
    path('discover_collection_page', views.discover_collection_page),
    path('create_collection_page/<int:user_id>', views.create_collection_page),
    path('create_collection/<int:user_id>', views.create_collection),
    path('edit_collection_page/<int:collection_id>', views.edit_collection_page),
    path('edit_collection/<int:collection_id>', views.edit_collection),
    path('remove_collection/<int:collection_id>', views.remove_collection),
    path('add_to_collection/<str:business_id>', views.add_to_collection),
    path('add_restaurant/<int:collection_id>/<int:restaurant_id>', views.add_restaurant),
    path('add_photo/<int:collection_id>', views.add_photo),
    path('discover_collection_detail/<int:collection_id>', views.discover_collection_detail),
    path('collection_detail/<int:collection_id>', views.collection_detail),
    path('remove_restaurant/<int:collection_id>/<int:restaurant_id>', views.remove_restaurant),
    path('add_user/<int:collection_id>/<int:user_id>', views.add_user),
    path('remove_user/<int:collection_id>/<int:user_id>', views.remove_user),
    path('like/<int:collection_id>', views.like),
    path('dislike/<int:collection_id>', views.dislike),
    path('logout', views.logout),
    path('list_restaurants', views.list_restaurants),
    path('select_category', views.select_category),
    path('current_location_index', views.current_location_index),
    path('current_location_list_of_restaurants', views.current_location_list_of_restaurants)
]
