# Generated by Django 3.2.4 on 2021-12-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_collage_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='creators',
        ),
    ]
