# Generated by Django 3.2.4 on 2022-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_auto_20211223_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='foodie.User'),
        ),
    ]
