# Generated by Django 3.2.4 on 2022-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_collage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='photo',
            field=models.ImageField(default='', upload_to='collages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collage',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='foodie.User'),
        ),
    ]
