# Generated by Django 3.2.4 on 2022-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_auto_20220106_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='collections')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creators', models.ManyToManyField(related_name='creators', to='foodie.User')),
                ('likes', models.ManyToManyField(related_name='likes', to='foodie.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='collages',
        ),
        migrations.DeleteModel(
            name='Collage',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='collections',
            field=models.ManyToManyField(related_name='restaurants', to='foodie.Collection'),
        ),
    ]
